# Generated by Django 4.1.10 on 2023-08-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='url_img',
            field=models.CharField(default='', max_length=900),
        ),
    ]
