# Generated by Django 4.1.10 on 2023-08-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_books_url_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Price',
            field=models.CharField(default='', max_length=200),
        ),
    ]
